apiVersion: batch/v1
kind: Job
metadata:
  name:  minnie65-decimate-meshes
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      volumes: # Example volume mounting
      - name: mnt # name for the volume to be reference in container volumeMounts
        hostPath:
          path: /mnt # Directory on the host machine to be mounted
      containers:
      - name: minnie65-decimate-meshes
        image: at-docker.ad.bcm.edu:5000/decimation_skeletonization:latest
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts: # Container reference to volumes define above
        - name: mnt # Name of the volume define above
          mountPath: /mnt # Location of where to mount it in the container
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done;"] #../src/decimation_skeletonization/scripts/populate_decimation.py"]