apiVersion: batch/v1
kind: Job
metadata:
  name:  minnie65-decimate-meshes
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      volumes: # Example volume mounting
      - name: mnt # name for the volume to be reference in container volumeMounts
        hostPath:
          path: /mnt # Directory on the host machine to be mounted
      containers:
      - name: minnie65-decimate-meshes
        image: at-docker.ad.bcm.edu:5000/decimation_skeletonization:latest
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts: # Container reference to volumes define above
        - name: mnt # Name of the volume define above
          mountPath: /mnt # Location of where to mount it in the container
        env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        command: ["/bin/sh"]
        args: ["-c", "cd /src/decimation_skeletonization/python/MeshAfterParty && python3 -u populate_decimation.py"] #../src/decimation_skeletonization/scripts/populate_decimation.py"]